In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch 
from torch import nn
from torch.utils.data import DataLoader, Dataset

from sklearn.model_selection import train_test_split

In [2]:
font_title = {'family': 'Arial',
             'size': 18
             }

font_labels = {'family': 'Arial',
               'size': 16 
              }

font_ticks = {'family': 'Arial',
               'size': 14 
              }

font_ticks_dates = {'family': 'Arial',
               'size': 14,
                    'rotation':45
                   }

In [110]:
filepath = '../Modelling/Datasets/Temp_CDD_to_Disp.csv'
raw_data = pd.read_csv(filepath)

raw_data.dropna(inplace=True)
raw_data.reset_index(inplace=True)
raw_data

index    Datetime  Cr_sum_disp_ext1  Cr_sum_disp_ext2  CDD_Step_roof  \
0        0  2019-04-15               0.0              -1.0      12.341042   
1        1  2019-04-16              -1.0               0.0      10.111875   
2        2  2019-04-17              -1.0              -1.0       9.114583   
3        3  2019-04-18              -2.0               0.0       9.850833   
4        4  2019-04-19               0.0               0.0       9.417292   
..     ...         ...               ...               ...            ...   
119    119  2019-08-12            -249.0            -198.0      19.556042   
120    120  2019-08-13            -249.0            -198.0      18.597708   
121    121  2019-08-14            -248.0            -198.0      18.540833   
122    122  2019-08-15            -248.0            -198.0      18.433333   
123    123  2019-08-16            -245.0            -199.0      22.901429   

     CDD_Step_facade  Air_Temp_roof  Air_Temp_facade  RT_Delta  Cr_disp_ext1  \
0          12.794375      30.341042        30.341042  0.245833           0.0   
1          13.019583      28.111875        28.111875  0.183333          -1.0   
2          11.002083      27.114583        27.114583  0.008000           0.0   
3          11.072708      27.850833        27.850833 -0.008333          -1.0   
4          11.467917      27.417292        27.417292  0.020833           2.0   
..               ...            ...              ...       ...           ...   
119        21.997083      37.556042        37.556042  2.287500          -1.0   
120        22.040417      36.597708        36.597708  2.295833           0.0   
121        22.110833      36.540833        36.540833  2.250000           1.0   
122        23.065208      36.433333        36.433333  2.400000           0.0   
123        25.003077      40.901429        40.901429  2.366667           3.0   

     Cr_disp_ext2  
0            -1.0  
1             1.0  
2            -1.0  
3             1.0  
4             0.0  
..            ...  
119           0.0  
120           0.0  
121           0.0  
122           0.0  
123          -1.0  

[124 rows x 11 columns]

In [114]:
output_cols = ['Cr_disp_ext1']
input_cols = ['Air_Temp_roof', 'RT_Delta']

In [121]:
class TT95_Dataset(Dataset):
    def __init__(self, filepath, inputs, outputs):
        data = pd.read_csv(filepath)
        x = data[inputs].values
        print(x)
        y = data[outputs].values
        self.x_train = torch.tensor(x, dtype=torch.float32)
        self.y_train = torch.tensor(y, dtype=torch.float32)
        
    def __len__(self):
        return len(self.y_train)
    
    def __getitem__(self, idx):
        return self.x_train[idx], self.y_train[idx]

In [134]:
tt95_data = TT95_Dataset(filepath, input_cols, output_cols)
print(len(tt95_data))
dl_train = DataLoader(tt95_data, batch_size=4, shuffle=False)

[[ 3.03410417e+01  2.45833333e-01]
 [ 2.81118750e+01  1.83333333e-01]
 [ 2.71145833e+01  8.00000000e-03]
 [ 2.78508333e+01 -8.33333333e-03]
 [ 2.74172917e+01  2.08333333e-02]
 [ 2.64702083e+01  4.16666667e-02]
 [ 2.73127083e+01  8.33333333e-02]
 [ 2.87606250e+01  6.25000000e-02]
 [ 3.03043750e+01  9.58333333e-02]
 [ 3.13481250e+01  2.70833333e-01]
 [ 3.18289583e+01  4.58333333e-01]
 [ 3.07541667e+01  5.37500000e-01]
 [ 3.36225000e+01  5.25000000e-01]
 [ 3.43285417e+01  6.12500000e-01]
 [ 3.63218750e+01  7.20833333e-01]
 [ 3.70231250e+01  8.66666667e-01]
 [ 3.26581250e+01  1.19166667e+00]
 [ 3.22414583e+01  1.40416667e+00]
 [ 3.57652083e+01  1.22916667e+00]
 [ 3.42343750e+01  9.08333333e-01]
 [ 3.18043750e+01  9.79166667e-01]
 [ 3.02762500e+01  1.32500000e+00]
 [ 3.11614583e+01  1.20000000e+00]
 [ 3.21545833e+01  8.83333333e-01]
 [ 3.33754167e+01  6.79166667e-01]
 [ 3.42041667e+01  6.04166667e-01]
 [ 3.55920833e+01  7.00000000e-01]
 [ 3.61877083e+01  9.54166667e-01]
 [ 3.52670833e+01  1

In [135]:
for batch, (X,y) in enumerate(dl_train):
    print(X, y)

tensor([[ 3.0341e+01,  2.4583e-01],
        [ 2.8112e+01,  1.8333e-01],
        [ 2.7115e+01,  8.0000e-03],
        [ 2.7851e+01, -8.3333e-03]]) tensor([[ 0.],
        [-1.],
        [ 0.],
        [-1.]])
tensor([[2.7417e+01, 2.0833e-02],
        [2.6470e+01, 4.1667e-02],
        [2.7313e+01, 8.3333e-02],
        [2.8761e+01, 6.2500e-02]]) tensor([[ 2.],
        [-1.],
        [ 0.],
        [ 1.]])
tensor([[30.3044,  0.0958],
        [31.3481,  0.2708],
        [31.8290,  0.4583],
        [30.7542,  0.5375]]) tensor([[0.],
        [1.],
        [1.],
        [1.]])
tensor([[33.6225,  0.5250],
        [34.3285,  0.6125],
        [36.3219,  0.7208],
        [37.0231,  0.8667]]) tensor([[1.],
        [0.],
        [0.],
        [1.]])
tensor([[32.6581,  1.1917],
        [32.2415,  1.4042],
        [35.7652,  1.2292],
        [34.2344,  0.9083]]) tensor([[  0.],
        [  2.],
        [-19.],
        [  0.]])
tensor([[31.8044,  0.9792],
        [30.2763,  1.3250],
        [31.1615,  1.2

In [136]:
class TestMLP(nn.Module):
    def __init__(self, features):
        super(TestMLP, self).__init__()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(features, 322),
            nn.ReLU(),
            nn.Linear(322, 16),
            nn.ReLU(),
            nn.Linear(16, 1)
        )
        
    def forward(self, x):
        logits = self.linear_relu_stack(x)
        return logits

In [137]:
model = TestMLP(2)

In [138]:
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    for batch, (X,y) in enumerate(dataloader):
        pred=model(X)
        loss = loss_fn(pred, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        #if batch%2 == 0:
        loss, current = loss.item(), batch*len(X)
        print(f"loss: {loss:>7f} [{current:>5d}/{size:>5d}]")

In [142]:
loss_fn = nn.MSELoss()
learning_rate = 1e-3
epochs = 5
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------")
    train_loop(dl_train, model, loss_fn, optimizer)

Epoch 1
-------------------------
loss: 0.267384 [    0/  124]
loss: 2.530483 [    4/  124]
loss: 2.090027 [    8/  124]
loss: 1.519143 [   12/  124]
loss: 86.333130 [   16/  124]
loss: 1.964649 [   20/  124]
loss: 0.961544 [   24/  124]
loss: 77.357971 [   28/  124]
loss: 59.797787 [   32/  124]
loss: 46.043648 [   36/  124]
loss: 83.894905 [   40/  124]
loss: 91.408615 [   44/  124]
loss: 76.565018 [   48/  124]
loss: 0.282487 [   52/  124]
loss: 1.052178 [   56/  124]
loss: 148.823471 [   60/  124]
loss: 1.068592 [   64/  124]
loss: 94.197205 [   68/  124]
loss: 45.118507 [   72/  124]
loss: 1.090996 [   76/  124]
loss: 1.587386 [   80/  124]
loss: 93.518166 [   84/  124]
loss: 39.265495 [   88/  124]
loss: 1.608950 [   92/  124]
loss: 44.441254 [   96/  124]
loss: 1.009919 [  100/  124]
loss: 1.720539 [  104/  124]
loss: 1.004430 [  108/  124]
loss: 0.502414 [  112/  124]
loss: 83.926476 [  116/  124]
loss: 4.444586 [  120/  124]
Epoch 2
-------------------------
loss: 0.295176 [  